version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch

    # needed with autostop
    restart: no
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      FORGE_VERSION: "14.23.5.2860"
      VERSION: 1.12.2

      ENABLE_ROLLING_LOGS:  "true"

      ENABLE_AUTOSTOP: "true"
      # shouldn't be too small or else a backup could be created per startup
      # 8 hours in seconds
      AUTOSTOP_TIMEOUT_EST: 28800
      AUTOSTOP_TIMEOUT_INIT: 28800
      OVERRIDE_SERVER_PROPERTIES: "true"

      # resource constraints
      MAX_PLAYERS: "10"
      MAX_MEMORY: "8G"
      VIEW_DISTANCE: "8"

      # game preference
      CF_MODPACK_ZIP: /profile.zip
      CF_SLUG: "custom"
      # needed since incorrectly declared as server side when it's only client side
      CF_EXCLUDE_MODS: "244447"
      DIFFICULTY: "hard"
      LEVEL: "word-data"
      ENABLE_COMMAND_BLOCK: "true"
      ENABLE_WHITELIST: "true"
      RCON_CMDS_STARTUP:  |-
        gamerule mobGriefing false
        gamerule commandBlockOutput false
        gamerule logAdminCommands false
    
    depends_on:
      restore-backup:
        condition: service_completed_successfully

    volumes:
      - ./data:/data
      - ./modpack-client/profile.zip:/profile.zip:ro

    env_file:
      - .env
  
  restore-backup:
    image: itzg/mc-backup
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      - ./data:/data
      - ./data_backup:/backups:ro
  
  backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
      BACKUP_INTERVAL: "1d"
      PRUNE_BACKUPS_DAYS: 7

      TAR_COMPRESS_METHOD: "zstd"
      ZSTD_PARAMETERS: "-10 --long=25 --single-thread"
    volumes:
      - ./data:/data:ro
      - ./data_backup:/backups
