version: "3"

services:
  mc:
    image: itzg/minecraft-server:java25

    # needed with autostop
    restart: no
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "true"

      TYPE: FORGE
      VERSION: "1.12.2"

      # https://github.com/CleanroomMC/Cleanroom/issues/638
      FORGE_INSTALLER_URL: https://github.com/CleanroomMC/Cleanroom/releases/download/0.5.15-alpha/cleanroom-0.5.15-alpha-installer.jar
      MODS: |
        https://github.com/CleanroomMC/Fugue/releases/download/0.22.6/+Fugue-0.22.6.jar
        https://github.com/CleanroomMC/Scalar/releases/download/2.11.1/scalar-1.12.2-2.11.1.jar

      GENERIC_PACK: /pack.zip

      ENABLE_ROLLING_LOGS: "true"
      ROLLING_LOG_MAX_FILES: "5"

      ENABLE_AUTOSTOP: "true"
      # shouldn't be too small or else a backup could be created per startup
      # 8 hours in seconds
      AUTOSTOP_TIMEOUT_EST: 28800
      AUTOSTOP_TIMEOUT_INIT: 28800
      OVERRIDE_SERVER_PROPERTIES: "true"

      # resource constraints
      MAX_PLAYERS: "10"
      MAX_MEMORY: "10G"
      VIEW_DISTANCE: "8"
      # some large number - 10 minutes
      MAX_TICK_TIME: "600000"

      # game preference
      DIFFICULTY: "hard"
      LEVEL: "world-data"
      ENABLE_COMMAND_BLOCK: "true"
      ENABLE_WHITELIST: "true"
        # RCON_CMDS_STARTUP:  |-
        # gamerule mobGriefing false DISABLED BY MOD
        # other game rules also disabled by mod by default
        # gamerule commandBlockOutput false
        # gamerule logAdminCommands false

    depends_on:
      restore-backup:
        condition: service_completed_successfully

    volumes:
      - ./data:/data
      - ./pack.zip:/pack.zip:ro

  restore-backup:
    image: itzg/mc-backup
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      - ./data:/data
      - ./data_backup:/backups:ro

  backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
      BACKUP_INTERVAL: "1d"
      PRUNE_BACKUPS_DAYS: 7
      PRUNE_BACKUPS_COUNT: 7

      TAR_COMPRESS_METHOD: "zstd"
      ZSTD_PARAMETERS: "-10 --long=25 --single-thread"
    volumes:
      - ./data:/data:ro
      - ./data_backup:/backups