version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch

    # needed with autostop
    restart: no
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      FORGE_VERSION: "14.23.5.2860"
      VERSION: 1.12.2

      ENABLE_ROLLING_LOGS:  "true"

      ENABLE_AUTOSTOP: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"

      # resource constraints
      MAX_PLAYERS: "10"
      MAX_MEMORY: "8G"
      VIEW_DISTANCE: "8"

      # game preference
      CF_MODPACK_ZIP: /profile.zip
      CF_SLUG: "custom"
      DIFFICULTY: "hard"
      LEVEL: "word-data"
      ENABLE_WHITELIST: "true"

    volumes:
      - ./data:/data
      - ./modpack-client/profile.zip:/profile.zip:ro

    env_file:
      - .env